version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test
          command: make test
      - run:
          name: Logg into Docker registry
          command: docker login -u $docker_user -p $docker_password dokken.azurecr.io
      - run:
          name: Create docker image
          command: make build
      - run:
          name: Publish docker image
          command: make push

workflows:
  version: 2
  commit:
    jobs:
      - build
