version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
    - image: circleci/golang:1.13.0
    working_directory: /go/src/github.com/SparebankenVest/azure-key-vault-to-kubernetes
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Test
        command: make test
    - run:
        name: Create docker image
        command: make build
    - run:
        name: Logg into Docker registry
        command: docker login -u $docker_user -p $docker_password dokken.azurecr.io
    - run:
        name: Publish docker image
        command: make push

  release:
    docker:
    - image: circleci/golang:1.13.0
    working_directory: /go/src/github.com/SparebankenVest/azure-key-vault-to-kubernetes
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Pull images to release
        command: |
            docker login -u $docker_user -p $docker_password dokken.azurecr.io
            make pull-release
    - run:
        name: Logg into public Docker registry
        command: |
            docker login -u $docker_release_user -p $docker_release_password
            make release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*).*$/
            branches:
              ignore: /.*/


      