apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azuremanagedidentities.spv.no
  labels:
    app.kubernetes.io/name: akv2k8s
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: spv.no
  names:
    kind: AzureManagedIdentity
    listKind: AzureManagedIdentityList
    plural: azuremanagedidentities
    singular: azuremanagedidentity
    shortNames:
    - ami
    categories:
    - all
  scope: Namespaced
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              required: ['name']
              properties:
                name:
                  type: string
                  description: Name of the Azure Managed Identity to
