name: build and deploy to private repo

on:
  push:
    branches:
    - master
    paths:
    - 'go.mod'
    - 'go.sum'
    - 'cmd/**'
    - 'pkg/**'
    - '!docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'

    - name: Test
      run: make test

    - name: Build docker images
      run: make build

    - name: Push images to public repo
      run: |
        docker login -u ${{secrets.PUBLIC_REGISTRY_USERNAME}} -p ${{secrets.PUBLIC_REGISTRY_PASSWORD}}
        make release DOCKER_RELEASE_TAG=${GITHUB_REF##*/}

    - name: Push images to private repo
      run: |
        docker login -u ${{secrets.PRIVATE_REGISTRY_USERNAME}} -p ${{secrets.PRIVATE_REGISTRY_PASSWORD}} dokken.azurecr.io
        make push
        