name: Build WebHook

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build-webhook.yaml'
    - '.github/actions/**'
    - 'Makefile'
    - 'go.mod'
    - 'go.sum'
    - 'cmd/azure-keyvault-secrets-webhook/**'
    - 'pkg/**'
    - '!docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'

    - name: Build
      uses: ./.github/actions/build
      with:
        build-make-action: build-webhook

    - name: Push
      uses: ./.github/actions/push
      with:
        push-make-action: push-webhook
        docker-user: bogus
        docker-passw: ${{ secrets.FAKE_SECRET }}
