name: Build Controller

on:
  push:
    branches:
    - master
    - '*-patch'
    paths:
    - '.github/workflows/controller-build.yaml'
    - '.github/actions/**'
    - 'Dockerfile'
    - 'Makefile'
    - 'go.mod'
    - 'go.sum'
    - 'cmd/azure-keyvault-controller/**'
    - 'pkg/**'
    - '!docs/**'
    - '!crds/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'

    - name: Build
      uses: ./.github/actions/build
      env:
        AKV2K8S_CLIENT_ID: ${{ secrets.INT_TEST_CLIENT_ID }}
        AKV2K8S_CLIENT_SECRET: ${{ secrets.INT_TEST_CLIENT_SECRET }}
        AKV2K8S_CLIENT_TENANT_ID: ${{ secrets.INT_TEST_TENANT_ID }}
        AKV2K8S_AZURE_SUBSCRIPTION: ${{ secrets.INT_TEST_SUBSCRIPTION }}
      with:
        build-make-action: image-controller

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true

    - name: Output version
      run: |
        echo "Next version ${{ steps.tag_version.outputs.new_tag }}"

    - name: Push
      uses: ./.github/actions/push
      with:
        push-make-action: push-controller
        docker-user: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
        docker-passw: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
