apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-keyvault-controller
  namespace: spv-system
  labels:
    app: azure-keyvault-controller
    aadpodidbinding: azure_key_vault # Binding from AzureIdentityBinding
spec:
  selector:
    matchLabels:
      app: azure-keyvault-controller
  template:
    metadata:
      labels:
        app: azure-keyvault-controller
        aadpodidbinding: azure_key_vault # Binding from AzureIdentityBinding
    spec:
      serviceAccountName: azure-keyvault-controller
      containers:
      - name: azure-keyvault-controller
        image: dokken.azurecr.io/azure-keyvault-controller:0.0.32
        imagePullPolicy: Always
        env:
        - name: AZURE_VAULT_NORMAL_POLL_INTERVALS
          value: 10m
        - name: AZURE_VAULT_EXCEPTION_POLL_INTERVALS
          value: 30m
        - name: AZURE_VAULT_MAX_FAILURE_ATTEMPTS
          value: "5"
        # - name: LOG_LEVEL
        #   value: debug
